// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkoyiiyrfabqqaamhucu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rb3lpaXlyZmFicXFhYW1odWN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4MDMwOTcsImV4cCI6MjA1MDM3OTA5N30.y8zfdB09HKp6tGFYDAFIRBBHIK4YVNUEBEd1qXtH35U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);